title: Chaitanya Khoje
email: contact@chaitanyakhoje.com
description: >-
  Astrophotographer capturing the wonders of the cosmos through telescopes and cameras.
  Specializing in deep sky objects, galaxies, and nebulae.
baseurl: ""
url: "https://chaitanyakhoje.github.io"

# Social media
github_username: chaitanyakhoje
instagram_username: chaitanyakhoje

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  gallery_items:
    output: true
    permalink: /gallery/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "gallery_items"
    values:
      layout: gallery_item

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md
  - Rakefile
  - .github